"""init db

Revision ID: 09d8f34ccc28
Revises: 
Create Date: 2023-04-25 00:10:05.094730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d8f34ccc28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.VARCHAR(), nullable=True),
    sa.Column('mute_time', sa.SmallInteger(), nullable=True),
    sa.Column('num_warnings', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_tg_id')
    )
    op.create_index(op.f('ix_chat_chat_tg_id'), 'chat', ['chat_tg_id'], unique=False)
    op.create_table('user_chat',
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('num_warnings', sa.Integer(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_tg_id', 'chat_tg_id')
    )
    op.create_index(op.f('ix_user_chat_chat_tg_id'), 'user_chat', ['chat_tg_id'], unique=False)
    op.create_index(op.f('ix_user_chat_user_tg_id'), 'user_chat', ['user_tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chat_user_tg_id'), table_name='user_chat')
    op.drop_index(op.f('ix_user_chat_chat_tg_id'), table_name='user_chat')
    op.drop_table('user_chat')
    op.drop_index(op.f('ix_chat_chat_tg_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
