"""add table chat_message

Revision ID: 1438b1a78590
Revises: edb8bf3f7ca7
Create Date: 2023-04-28 13:22:21.859286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438b1a78590'
down_revision = 'edb8bf3f7ca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.TEXT(), nullable=True),
    sa.Column('message_len', sa.Integer(), nullable=True),
    sa.Column('isToxic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_tg_id', 'chat_tg_id', 'message_id')
    )
    op.create_index(op.f('ix_chat_message_chat_tg_id'), 'chat_message', ['chat_tg_id'], unique=False)
    op.create_index(op.f('ix_chat_message_message_id'), 'chat_message', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_message_user_tg_id'), 'chat_message', ['user_tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_user_tg_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_tg_id'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
