"""alter table user_chat add message_counter

Revision ID: bb617bc271b4
Revises: cae3f95f47a2
Create Date: 2023-05-03 17:37:22.121775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb617bc271b4'
down_revision = 'cae3f95f47a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat', sa.Column('message_counter', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat', 'message_counter')
    # ### end Alembic commands ###
