"""alter table user_chat,chat counter_messages nullable=False 

Revision ID: dfc3fc7e3e54
Revises: bb617bc271b4
Create Date: 2023-05-03 21:41:16.243686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc3fc7e3e54'
down_revision = 'bb617bc271b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'message_counter',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_chat', 'message_counter',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_chat', 'message_counter',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chat', 'message_counter',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
